### ISSUE TITLE
Was the invoice paid? How to verify

### ISSUE THREAD

**Issue by IntinteDAO** [BlueWallet/LndHub#104]
Hello, I have a small problem with the API that I don't know clearly how to solve.

I authorize myself to LNDHub and generate an invoice. Can you directly check if the invoice is paid? I know that such information is in getuserinvoices, but it requires checking all invoices (which is not a big problem, but every time the server has to send a lot of data).

Maybe there is a way to get a payment confirmation having a specific Invoice (if it is in the LNDHub database for that user, of course).

**Comment by Overtorment** [comment]
yes, there is a route for that

```
router.get('/checkpayment/:payment_hash'
```
