### ISSUE TITLE
How to check routing?

### ISSUE THREAD

**Issue by IntinteDAO** [BlueWallet/LndHub#107]
The documentation for Payinvoice says that the routing has to be checked before sending payinvoice (whether it is possible to execute the transaction correctly). There are two functions to this in the documentation, but none of them works correctly:
- /checkroute does not exist in the LNDHub code? 
- checkrouteinvoice does the same as decodeinvoice

Do I do something wrong or do these functions not work properly? Or how they should look if the LNDHub documentation is wrong.

**Comment by Overtorment** [comment]
the correct call name is `/checkrouteinvoice`, and its not implemented in Lndhub. its actually about to get removed completely as not necessary from both client (bw) and server. latest LND is actually pretty good at routing and at failing fast if there's no route. plus, if you run your own lndhub you probably making sure its pretty good connected, so your payment success rate is 99%+.
skipping doing `checkrouteinvoice` will subjectively make payments feel even faster for end users.

PS. don't rely on LND official docs too much, they get obsolete pretty fast

**Comment by IntinteDAO** [comment]
Closing :P
