### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by AaronDewes** [BlueWallet/LndHub#122]
I'm using LNDHub in a docker environment. When trying to connect it to BlueWallet, I get that it's not a valid LNDHub URL. It seems like there are authentication issues with the API, but I'm not sure why. The LNDHub front page works as expected. The logs display no errors/warnings. What am I doing wrong there?

**Comment by ncoelho** [comment]
what is the uri format you are inserting?

**Comment by AaronDewes** [comment]
I've tried:

- Creating a tor Hidden service for LNDHub
- http://mydomain:3000
- http://mydomain/lndhub

All three did show the dashboard, but didn't connect

**Comment by ncoelho** [comment]
Does it connect without tor?

**Comment by AaronDewes** [comment]
No, neither tor nor without tor works

**Comment by Overtorment** [comment]
try `https`. your phone might have a policy to forbid unencrypted http communications

**Comment by AaronDewes** [comment]
Fixed it
