### ISSUE TITLE
DB querry and edit

### ISSUE THREAD

**Issue by centinel20** [BlueWallet/LndHub#126]
I read through the resolved issues and followed this:
https://github.com/BlueWallet/LndHub/issues/60#issuecomment-606615397
I can get the users from the database and then use the script but all of my users appear with 0 balance and no transactions. There is a deprecation warning on the output.

Is there a new way to see the wallets and theyr balances?
Is there a way to add funds to a certain account manually?

**Comment by Overtorment** [comment]
script should work, nothing principally changed. maybe you're not using correct userids.
when `keys` command gives you a list of records, its not userids yet. its keys to lookup userids. for example
`user_aaa_bbb` you then need to get this key in redis console `get user_aaa_bbb` and that one will give you userid. see https://github.com/BlueWallet/LndHub/blob/master/doc/schema.md

the easiest way is to add an invoice (or fake a record in user's `userinvoices_for_{userid}`) and then mark it as paid (`ispaid_{payment_hash} = 1`)
