### ISSUE TITLE
What should I backup?

### ISSUE THREAD

**Issue by ale-rinaldi** [BlueWallet/LndHub#129]
Hello,

I managed to install my own LndHub instance on a Debian server. What should back up to be able to restore the exact situation if the server catches fire?

From LND I'm backing up the entire .lnd folder on a regular basis.

What about LndHub? Should I back up the Redis instance? I also suggest to mention this in the documentation, I think it's a must-have information.

Thanks for your great work!

**Comment by Overtorment** [comment]
thanks!
ok, if you care about user accounts, then yes, redis database backup is a must. if not - all fund are still in LND, so you only need lnd's mnemonic seed and channels backup (which is basically `~/.lnd` folder)

**Comment by xraid** [comment]
what are BLW using for its backend to there build of LndHub ?

is it postgress

**Comment by xraid** [comment]
interesting - echo chamber here hello hello

silence

**Comment by ncoelho** [comment]
> interesting - echo chamber here hello hello
> 
> 
> 
> silence 

The lndhub repo is open an anyway can see it. It is written there.

Not sure why someone should invest their time replying to this

**Comment by xraid** [comment]
what are BLW using for its backend to their build version of LndHub ?

is it postgress

**Comment by xraid** [comment]
i am adding a adapter to LndHub that can have several stores as connectors the adapter

Redis
Redis
Sqlite3
Postgress
Mongo
MySql

"Not sure why someone should invest their time replying to this" 

and I am not shure i PR here . just fork seems more sane 

thanks

**Comment by ncoelho** [comment]
Only runs with Redis.

**Comment by xraid** [comment]
so to make it clear BlueWallet's default LN backend only runs on Redis ?

**Comment by ncoelho** [comment]
> so to make it clear BlueWallet's default LN backend only runs on Redis ?

I'm not understanding where is the doubt. Yes, Redis.

**Comment by xraid** [comment]
i imagine you have a lot of tx passing through so the accounting and reporting stats helpdesk etc. would be more flexible with a db made for such requests with joins ++

so i was curious se what You use as backend for BlueWallet users there and if You have a special build with added functionality

**Comment by Overtorment** [comment]
lndhub is the backend for lighning for bluewallet. there is nothing else
