### ISSUE TITLE
Lndhub and Tor

### ISSUE THREAD

**Issue by centinel20** [BlueWallet/LndHub#135]
I use a mynode premium and can connect bluewallet to my electrum server through tor. However although I do have a .onion adress and a port for it ( 3000/30001) i cannot connect to my LNDhub from bluewallet. The error I get states: not a valid URI.

**Comment by Overtorment** [comment]
bluewallet doesnt support Lndhub through TOR yet, but its coming, you can follow progress here: https://github.com/BlueWallet/BlueWallet/pull/2295
