### ISSUE TITLE
Cannot pay to peers with private channels

### ISSUE THREAD

**Issue by taxmeifyoucan** [BlueWallet/LndHub#149]
Trying to pay invoice with hints to receive via private channels using LndHub instance always fails. For example, I am not able to send to Phoenix wallet or BLW with hosted channel. I tested this using BlueWallet and Zeus with LndHubs - herokuapp public instance and my also my own instance. In all cases, it fails to transact. 
Not being able to transact to other major wallet like Phoenix makes this a real problem. For instance, receiving from Phoenix works but sending back doesn't not. Error is always `no route`. In LndHub logs, I can see payment was approved but in LND logs, it immediately says that route was not found. With the same LND instance, same invoice can be paid successfully using `lncli` .

**Comment by Overtorment** [comment]
hmm, i have just tried breez (priv channel, routing hints) and it worked for me.
what amount have you tried? cause i tried 10k sat and 15k sat and it worked okay.
my guess is that you tried too small amount, like, 1sat, and lndhub has feelimit to it, like, the fee would be 1.1 sat, and lndhub says are you nuts, that's 110% fee for your payment, lets not do it
