### ISSUE TITLE
Add notes on HTTPS in README

### ISSUE THREAD

**Issue by BtcContributor** [BlueWallet/LndHub#173]
Hi,
I would like HTTPS instruction to be added to README.
I would like to do that by myself but I am not sure how to do that :)

**Comment by Overtorment** [comment]
what instructions?

**Comment by BtcContributor** [comment]
I mean, no mention to how to add HTTPS to lndhub so most people will end using HTTP and this is bad.
Steps to do that would be very useful.

**Comment by Overtorment** [comment]
people who install lndhub are expected to know how to deal with tls certificates.
and if you're deploying to heroku or similar certificates are sorted for you

**Comment by Overtorment** [comment]
anyway, running tls termination and reverse proxy is out of scope for this repo
