### ISSUE TITLE
Stupid Question: Why do we need LNDHub?

### ISSUE THREAD

**Issue by maltokyo** [BlueWallet/LndHub#186]
I need some education here.

Other Lightning wallets like Zap, Zeus, etc, simply connect directly to LNS through gRPC or REST connections, without a "hub" in the middle like LNDHub.

What benefits does the LNDHub & Bluewallet combination bring over other lightning wallets like the above?

I have a running instance of LNDHub, simply because I want to use Bluewallet, so technically I understand the setup, but whilst using it, I really don't understand why it is needed in the first place!  Sorry for the stupid q if it is..
Thanks!

**Comment by maltokyo** [comment]
Another reason I ask: is that on the front page it says that LNDHub provides "separate accounts" to users.  But when I open a channel through Bluewallet on my own LNDHub, it simply opens a normal channel in my LND instance.  What am I missing?  Thanks for the help again, anyone who can shed light on this.

**Comment by Overtorment** [comment]
you could host single Lnd + Lndhub, and onboard your whole family, friends (and even more people), to lightning. through your node.
you would be managing channels & liquidity for them, while they would just happily use it (and deposit onchain bitcoins to top up their balances)
