### ISSUE TITLE
Installation guides for Umbrel

### ISSUE THREAD

**Issue by jaonoctus** [BlueWallet/LndHub#187]
I think we should add installation guides for Umbrel on README.md

**Comment by Overtorment** [comment]
what would that be? 
i thought its a one-click install from umbrel ui

**Comment by jaonoctus** [comment]
@Overtorment NIT

It is pretty straight forward. 

The idea here is just to make it clear on the README that LNDHub is now supported by Umbrel

**Comment by Overtorment** [comment]
its also on mynodebtc, and who knows where.
this repo is only for technical people. and not much people look here anyway
