### ISSUE TITLE
Failed to run build/index.js

### ISSUE THREAD

**Issue by klementtan** [BlueWallet/LndHub#195]
Received this error message when running `node build/index.js`
```bash
/Dependency/LndHub/build/node_modules/frisbee/lib/index.js:322
            _this.abortTokenMap.delete(options.abortToken);
                                ^^^^^^

SyntaxError: Unexpected token 'delete'
```

Running on Ubuntu 20.10

**Comment by Overtorment** [comment]
how did you build it?
recommended way to run it is just `npm start` which runs `node_modules/.bin/babel-node index.js`

**Comment by klementtan** [comment]
That works thanks!
