### ISSUE TITLE
Can't fund wallet "Requested wallet does not exist or is not loaded"

### ISSUE THREAD

**Issue by 634-5789** [BlueWallet/LndHub#242]
Environment:
Bitcoin Core v0.21.1
lnd 0.13.0-beta

I'm trying to fund a newly generated lightning wallet. I can see the satoshis arriving at my lightning node but they never show up in the wallet itself. Refreshing the wallet generates an error on the server:

`2021-07-05T13:12:59.702Z : info: [/getpending] : ["0017cd3c-6841-47b5-9c14-a9d493f00236","userid: e05dbf25f0769bfd3fe2efd10efeabc47fe732267b215415"]
listtransactions error: { Error: {"result":null,"error":{"code":-18,"message":"Requested wallet does not exist or is not loaded"},"id":"0fc84120-8a83-4c2a-be54-189d4048cf7a"}`

config.js looks like this

let config = {
  enableUpdateDescribeGraph: false,
  postRateLimit: 100,
  rateLimit: 200,
  bitcoind: {
    rpc: 'http://uuu:ppp@127.0.0.1:8332/wallet/wallet.dat',
  },
  redis: {
    port: 6379,
    host: '127.0.0.1',
    family: 4,
    db: 0,
  },
  lnd: {
    url: '127.0.0.1:10009',
  },
};

if (process.env.CONFIG) {
  console.log('using config from env');
  config = JSON.parse(process.env.CONFIG);
}

module.exports = config;

Any hints on how to solve this?

**Comment by Overtorment** [comment]
well you can practically get rid of `bitcoind` part in config, and lndhub will use LND's built-in wallet.

if you want to fix this particular error - you need to fix your bitcoind - use cli to check which wallets exist, and create one if needed (probably should be named as 'wallet' or 'wallet.dat', not sure )

**Comment by 634-5789** [comment]
Thanks a ton, removing the bitcoind part in config.js solved it.
