### ISSUE TITLE
How to verify that Redis stores to disc correctly.

### ISSUE THREAD

**Issue by ohenrik** [BlueWallet/LndHub#26]
In the readme you write:

> Don't forget to enable disk-persistance for redis.

I installed redis through the default apt-get command. So i am not sure i have this enabled. Through a bit of googling i came accross this example: https://gist.github.com/mathieue/5253651

Should i update my redis config file to have `appendfsync everysec` and `appendonly yes`? Or are the defaults ok? I assume the settings should be set so that if the server crashes users do not loose their funds?

A more detailed documentation would be helpful, I can contribute to this with what i know :)

**Comment by iamjackharper** [comment]
Wait for an official answer by the team to be sure, but `appendonly yes` is the solution I used, you can check the process in my guide [here](https://bitcoinmirror.ghost.io/how-to-install-bitcoin-lightning-and-lndhub-on-your-own-vps/)

**Comment by ohenrik** [comment]
Thank you for answering :) I have added appendonly and set `appendfsync always` instead og every second, as it seems that would be the safest (although slowes) way to ensure that no data is lost.
