### ISSUE TITLE
HTLC failure does not complete

### ISSUE THREAD

**Issue by yuyaogawa** [BlueWallet/LndHub#269]
I keep getting unilateral close from lndhub. I assume it is due to HTLC failure deos not complete. The log below is what I got from my node.

```
2021-08-02 02:31:36.421 [ERR] HSWC: ChannelLink(693418:1500:1): failing link: unable to complete dance with error: remote unresponsive
2021-08-02 02:31:36.574 [INF] BTCN: New valid peer 34.73.79.114:8333 (outbound) (/btcwire:0.5.0/btcd:0.20.0/)
2021-08-02 02:31:36.594 [INF] HSWC: ChannelLink(693418:1500:1): exited
```

After the HTLC remains for a certain time of period (based of timelock), lndhub unilateral closes the channel. I found an issue below which may cause unilateral close if two nodes version are different.
https://github.com/lightningnetwork/lnd/issues/5324#issuecomment-855863480

My LND node version is `0.12.1-beta`. What version does lndhub.io use?

**Comment by Overtorment** [comment]
lndhub.io uses `v0.13.0-beta.rc5-dirty`
closing channels when having pending htlc is a by-design behavior for all lightning nodes.

also, lndhub doesn't close channels, its entirely up to the underlying lnd.
so if you're having issues,  pls raise take them at lnd repo.

**Comment by nina1234** [comment]
Hi
