### ISSUE TITLE
Fill up lndhub account from main lnd account?

### ISSUE THREAD

**Issue by TheCherry** [BlueWallet/LndHub#295]
Hi,

I did setup a lnd node with umbrel and installed lndhub, as far as good.
Now then I create a "sub wallet" with my mobile phone and want send values from my lnd node to this sub wallet, the UI tells me " self-payments not allowed".

How can I charge the sub wallets from lndhub with my lnd liquid?

Greetings

**Comment by Overtorment** [comment]
easiest way is to depisot onchain. its still your money, they land on lnd's internal onchain wallet, you can use them later to fund a channel etc.

**Comment by xraid** [comment]
use `lncli payinvoice` in the umbrel terminal and add the `--allow_self_payment` flag
for a (made in BlueWallet) LN(card) invoice

is another method
