### ISSUE TITLE
partnerid mandatory or not?

### ISSUE THREAD

**Issue by MG-ng** [BlueWallet/LndHub#296]
It say in the LndHub/doc/Send-requirements.md  
> "partnerid" : "bluewallet" // string, not mandatory parameter

But in the code it seems like it has to exist and has to be equals "bluewallet". 
https://github.com/BlueWallet/LndHub/blob/35fe816d0aa5047653c2ff90d800ef146c31292c/controllers/api.js#L136

Is it intended to be that way, so that every alternative partner has to adjust this code or just use the bluewallet partnerid resulting in a useless parameter? 
Or am I reading the code wrong? (I am not that familiar with nodejs)

Thanks for your reply :)

**Comment by Overtorment** [comment]
its a bug. this should be relaxed and partnerid should be any string.

**Comment by MG-ng** [comment]
Okay, thanks

**Comment by Overtorment** [comment]
sure

**Comment by MG-ng** [comment]
#297
