### ISSUE TITLE
Bluewallet & lndHub, Refilled but still balance 0 and no transaction history

### ISSUE THREAD

**Issue by tobg** [BlueWallet/LndHub#30]
Hello,
cannot refill my bluewallt lightning wallet connected to lndhub, lnd 5.2 beta 3 and btc core 17.0. No transaction history is shown as well. There is no error in the lndhub log.
I can see, that tx is incomming and confirmed by lnd, but this is not reflecting inside my bluewallet. Have tried other transactions too. All tx has more than 6 confirmations.

Any ideas?

**Comment by Overtorment** [comment]
Are you runing butcoind with accounts feature enabled?

**Comment by tobg** [comment]
Yes, this is my bitcoind.conf


mainnet=1
[main]
printtoconsole=1
rpcallowip=::/0
rpcport=43782
port=39388
whitelist=0.0.0.0/0
deprecatedrpc=accounts
rpcuser=**********
rpcpassword=*******
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333

**Comment by tobg** [comment]
It works now. Was error 37 (the guy in front of the screen).
bitcoind was configured with wallet disabled and i removed that, but did not created a new lightning wallt. Used the old one from before the change inside bitcoind.conf.
