### ISSUE TITLE
Unable to start LndHub after update

### ISSUE THREAD

**Issue by ohenrik** [BlueWallet/LndHub#31]
hi i tried updating LndHub to the latest commit on the master branch. This resulted me being unable to restart LndHub. I get this error: `bitcoind failure`

After adding a print of the `err` variable here: https://github.com/BlueWallet/LndHub/blob/master/controllers/api.js#L21

I got this:
```
bitcoind failure { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET' } 
```

So im guessing there is something wrong with the connection to bitcoind through rpc, however i cannot figure out what. It might also be something completely different :)

Got any ideas about what might be wrong?

NB I am able to use `bitcoin-cli getblockchaininfo` in the console.

**Comment by Overtorment** [comment]
Looks like connectivity, yeah. Try restarting bitcoind.
Also, if you rollback lndhub I bet you get the same result

**Comment by ohenrik** [comment]
I tried restarting bitcoind. I should probably dig a bit in how to test the bitcoin rpc connectivbity better. But is there a quick way to check if the RPC connection with a console command? Or is `bitcoin-cli` already using RPC?

Btw. I am also getting this warning:
`DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead`

**Comment by Overtorment** [comment]
Bundled rpc client is good enough. Example

./bin/bitcoin-cli -rpcclienttimeout=30  -rpcport=8442  -rpcuser=user
-rpcpassword=pass     getblockchaininfo

You can run it from other host to test connectivity.

Grpc warning is unrelated

**Comment by ohenrik** [comment]
Thank you, running this command:
`bitcoin-cli -rpcclienttimeout=30  -rpcport=8332  -rpcuser=my_user -rpcpassword=my_password getblockchaininfo`

I get the correct response. However i noticed that the port i had in the config was wrong. Not sure why this was not a problem with the old setup. However switching from 8333 to 8332 fixed this issue.
