### ISSUE TITLE
HTTPS implementation

### ISSUE THREAD

**Issue by clonmac** [BlueWallet/LndHub#33]
I feel like LndHub should be using or at least promoting the use of HTTPS by default considering the fact that LN invoices and other sensitive auth information is being transmitted back and forth from the wallet to LndHub. A lot of the tutorials I've seen for getting this set up for individuals don't cover this glaring security omission and I feel like there will be a large number of users running their own LndHub implementation that could be easily compromised without encryption of the data in transit.

I think to start, by default, LndHub should start up with https.createServer().listen(); with configurable certificate paths for users to utilize. This will at least demonstrate to those looking to implement LndHub the need for HTTPS and a proper certificate.

My own implementation is using this and I also see that lndhub.io is utilizing it, so I think it would be good to have this repo acknowledge the need for HTTPS as well.

Thoughts?

**Comment by Overtorment** [comment]
TLS termination is up to end-user. Nginx, heroku, cloudflare etc. 
Its a good idea to include "hardening for production" section in readme.
And yeah, I totally forgot that nodejs can actually handle TLS on its own...

**Comment by clonmac** [comment]
Ya, even a disclaimer in the readme would probably suffice, just to help with the awareness of it.

**Comment by ianthius** [comment]
I agree on this. I have begun experimenting with it in the last week and I was scratching my head on this one a bit.
