### ISSUE TITLE
Invalid LNDHub URI

### ISSUE THREAD

**Issue by pookster45** [BlueWallet/LndHub#337]
Having trouble trying to pair BlueWallet with MyNode LNDHub. I get the error message "Invalid LNDHub URI" in BlueWallet when scanning -or- entering into Lightning Settings on the app. This had worked in the past (~3months ago) but have changed phones and am trying to pair on my new one. Thanks!

**Comment by Overtorment** [comment]
send me your node uri or qr code to i@bluewallet.io Ill take a look

**Comment by HammerHammock** [comment]
Is there any Solution available? I have the same Problem

**Comment by floydianslips** [comment]
Having this issue trying to connect to an Umbrel server as well.

**Comment by ichbinder** [comment]
I have the same Problem, with my Umbrel server as well.

**Comment by masterno12** [comment]
I have the same Problem, with my Umbrel server as well. Under Linux server...

**Comment by 12hourdrive** [comment]
I have the same issue is there still no solution?

**Comment by bradlives** [comment]
Hi, same issue as well, exactly as described

**Comment by BitcoinMechanic** [comment]
+1

**Comment by ro-le** [comment]
+1

**Comment by blastshielddown** [comment]
Have you tried enabling advanced mode in general settings? This should be done _before_ starting the process of creating a lightning wallet. Once advanced mode is enabled, you should be able to connect to your lndhub in settings under Network > Lightning Settings by scanning the QR code presented in the lndhub UI. Then you should be able to create a new lightning wallet that's connected to your lndhub.
