### ISSUE TITLE
manually assign value

### ISSUE THREAD

**Issue by Mazon** [BlueWallet/LndHub#37]
Is it possible to manually assign a wallet with funds from the node itself? Or best way to approach this user case. 

I operate a lightning node and use lndhub for my friends, to onboard them i want to ex send them 1 dollar. But cannot send to my own wallet directly from my lightning node since they are on the same node. 

lndhub wallet to lndhub wallet is after that fine. But don't have a good way of fund my own wallet except setting up external lightning wallet somewhere and then send back. Which is a bit of hassle.

**Comment by Overtorment** [comment]
Deposit to your ln wallet on lndhub via btc, and then send from ln to ln.
Transfers from lndhub account to lndhub account are easy

**Comment by Mazon** [comment]
Thanks, i was thinking some way to do without fee but one time i guess. Thank you.
