### ISSUE TITLE
Umbrel died with LndHub - where are the funds form my BlueWallet App wallet now?

### ISSUE THREAD

**Issue by feikede** [BlueWallet/LndHub#381]
My device running umbrel with LndHub has died and will never come back. I had configured BlueWallet App on my mobile to use the LndHub on that umbrel device as custodian. And I had moved some sats to that BW wallet by invoice.

Obviously, BlueWalletApp cannot connect to LndHub anymore - because the complete umbrel device has died and the onion address is gone. But BlueWalletApp still shows the funds on startup.

Where are these sats now? Will they recover in my lnd wallet when I restore from cipher?

Thanks!

**Comment by Overtorment** [comment]
if you have mnemonic phrase - this will easily restore onchain funds, and with some manipulations - funds from recently-closed channels. funds stuck in channels that arenot yet closed are considered 'zombie' and its kinda hard to get them out.
LND has long guides on all that.

**Comment by feikede** [comment]
Yeah, I know how to restore my lnd from the cipher phrase, thanks. The question was more about where the funds are that I have moved to the BW wallet app by invoice. The transactions list in BW App says "On-chain transaction". Does it sit on a BW App Wallet address on the bitcoin blockchain now? Think that would be kindof strange. Think I've chosen "Refill from external wallet" once to move the funds to BW App Wallet.

**Comment by feikede** [comment]
Ok, looks like it went like this:
(1) I sent funds from coinbase to BW App on-chain.
(2) BW App sent the funds to the lnd's wallet on-chain.
(3) Use BW App to pay something, that funds were deducted from any of the channels of my lnd off-chain.
(4) umbrel died
(5) restored lnd from 24-words cipher on another machine without umbrel, just bitcoind and lnd.
(6) lnd force-closed all channels and recovered on-chain funds.

But - I do not know how much sats were on the BW App when umbrel died.

**Comment by asaneh** [comment]
#402 #401 #400 #398 #399

**Comment by Overtorment** [comment]
anyway, bluewallet has no control of those funds, they are somewhere on LND & Umbrel, I suggest you raise your questions there.
