### ISSUE TITLE
transfer of funds between two accounts

### ISSUE THREAD

**Issue by fiksn** [BlueWallet/LndHub#42]
Probably a silly question, but is it possible to transfer funds between two user accounts on same node? As far as I understand there is just a balance in redis and when you pay for an invoice that acts as a cap and when you issue an invoice the system then keeps track and increases your balance eventually. In this way of course node operator can always change the state (and allow such a "transfer"). But can a normal user account through the API do such a thing as well?

**Comment by Overtorment** [comment]
Yes

**Comment by fiksn** [comment]
Thanks for the in-depth explanation ;)
I just felt this was not properly documented, this issue probably misses some "question" tag (which I wasn't able to add).

I read the code now and yeah https://github.com/BlueWallet/LndHub/blob/master/controllers/api.js#L152
It's done through decoding the user from invoice. So basically you `/payinvoice` but nothing happens on lightning or btc network if it's a different user on same server.
