### ISSUE TITLE
/getbalance should be /balance in the instructions

### ISSUE THREAD

**Issue by Alex-Horlock** [BlueWallet/LndHub#44]
![getbalance bug](https://user-images.githubusercontent.com/13980613/70473590-41a06200-1ac9-11ea-89bd-440b3cdbdb9a.png)

On your instructions page:

https://github.com/BlueWallet/LndHub/blob/8aa496938ed01442c6f16336b6ae503606aea558/doc/Send-requirements.md

It says at the top that the route to get the balance is /balance (which is correct) but further down it says it is /getbalance (which returns 404 error). An easy fix i hope!

P.S. thanks very much for this project... I used it for the first time tonight and it's great!

**Comment by Overtorment** [comment]
You are absolutely right! 
The document is outdated, reference client implementation is here https://github.com/BlueWallet/BlueWallet/blob/master/class/lightning-custodian-wallet.js
you can use it right away!

**Comment by lessless** [comment]
@Alex-Horlock , won't you mind sending a PR? This is quite a useful fix :)
