### ISSUE TITLE
Design-first API approach with RAML

### ISSUE THREAD

**Issue by yojoe** [BlueWallet/LndHub#45]
I created a RAML 1.0 API specification of the current LndHub implementation and published it at:
https://github.com/yojoe/lightninghub-api

The auto-generated HTML documentation can be found here: https://yojoe.github.io/lightninghub-api/

# Why RAML?
RAML allows a design-first API approach with: 

- automatic generation of human-readable HTML documentation
- automatic client/server code stubs generation for various languages (NodeJs, Go, Python, ...)
- round-trip engineering

Since there are at least two Bluewallet-compatible backend implementations right now ([LndHub](https://github.com/BlueWallet/LndHub) and [lntxbot](https://git.alhur.es/fiatjaf/lntxbot)), I think both projects would benefit from following a language independent, "stable" API specification.

One of the benefits for LndHub would be less code to maintain, as there are projects like [Osprey](https://github.com/mulesoft/osprey) which is Express middleware with automatic request validation.

What do you think?

**Comment by Overtorment** [comment]
How is it compared against OpenApi/Swagger?
