### ISSUE TITLE
Unable to access/import lightning wallet in bluewallet app using lndhub

### ISSUE THREAD

**Issue by PecusB** [BlueWallet/LndHub#476]
Hello,
my lightning wallet in bluewallet can no longer be used or imported (api error: bad auth (code 1)). I use my own umbrel server. I connected the electrum server and the bluewallet lndhub via qr codes, whichever worked fine. Creating new wallets works. I have the feeling that since the update of the lightning node to version 0.15.0-beta or the umbrel update to 0.50 it no longer works to access the created wallet. I haven’t changed anything and all of a sudden I no longer have the opportunity to access my credit. please give me some ideas what i can do.

**Comment by ncoelho** [comment]
That usually means your lndhub uri changed. Use the new one.

**Comment by PecusB** [comment]
Thanks for the answer. what exactly do you mean? I find the node uri in the umbrel settings but what should I do with it?

**Comment by PecusB** [comment]
Thanks for the answer. what exactly do you mean? i find the node uri in the umbrel settings but what should i do with it?

**Comment by PecusB** [comment]
> 

You don't mean the url that comes via the QR code, do you? I've already tried it all. With newly created wallets it works.

**Comment by Overtorment** [comment]
your lndhub backup should  looke smth like `lndhub://username:password@https://lndhub.io`

**Comment by PecusB** [comment]
Yes, the part after the "@" is exactly the same for new wallets I created for testing. Deleting and importing also works. Only with my old wallet with the credit always comes the error "bad auth (code 1). It can't really be the first part (username and password), can it?

**Comment by PecusB** [comment]
I give up. What is a backup for? Good thing it wasn't a lot of money.

**Comment by Overtorment** [comment]
are  you sure it was on default server? maybe service provider was some other lndhub installation.

send me your backup at i@bluewallet.io ill take a look

**Comment by PecusB** [comment]
Hi,
I have sent an e-mail.
Thank you very much.

**Comment by matiasvillaverde** [comment]
@Overtorment  I have the same problem. I just found a wallet that the default server was lndhub.io
