### ISSUE TITLE
Address reuse

### ISSUE THREAD

**Issue by bilthon** [BlueWallet/LndHub#514]
I've been going over the code and just found that apparently when requesting an on-chain deposit, addresses are reused per user. Is that desired long term? I understand that it is much simpler to just [set a redis key](https://github.com/BlueWallet/LndHub/blob/fb023b02be53b47a0b5b837001fc7b08dd7f3bd1/class/User.js#L103) that never expires per user and be done with it, but what about potential privacy implications of users depositing funds?

On the other hand if this is a custodial service, it by itself acts as a giant mixer, so there's some opacity in there already, users can deposit on-chain and withdraw via lightning and by doing so escape from simple chain analysis strategies.

So what are your ideas for this? is rotating addresses not a desired feature? Has it been discussed already?

**Comment by Overtorment** [comment]
this is by design. not considering privacy for a custodial service
