### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Th0rgal** [BlueWallet/LndHub#537]
Hello there,

I have a default lightning account created on Blue Wallet and I wonder how it works. I am familiar with lightning and the concept of channels, but I am not sure to understand how multiple accounts owned by different people can be created. Is LndHub some kind of centralized ledger on top of a single node? Does that mean the node operator could take my money?

Feel free to redirect me somewhere else if I don't ask at the right place.

Have a great day,
Thomas

**Comment by Overtorment** [comment]
https://bluewallet.io/BlueWallet-brings-zero-configuration-Lightning-payments-to-iOS-and-Android-30137a69f071/
