### ISSUE TITLE
How are tip invoices handled?

### ISSUE THREAD

**Issue by seanaye** [BlueWallet/LndHub#54]
Sorry, I don't know if theres a better place to ask this. 

How are internal tip invoices handled by LND hub? 

As far as I can tell the debit amount of a user's invoice is calculated in `getUserInvoices`

Assuming a tip invoice of amount 0 from internal User A => internal User B

Inside [`async getUserInvoices()`](https://github.com/BlueWallet/LndHub/blob/6b67839414f782c32fad07956b108fa6e39a63fe/class/User.js#L237)

LndHub would retrieve addInvoice rpc JSON for said tip invoice

[`let range = await this._redis.lrange('userinvoices_for_' + this._userid, 0, -1);`](https://github.com/BlueWallet/LndHub/blob/6b67839414f782c32fad07956b108fa6e39a63fe/class/User.js#L238)

And decode the pay request

[`let decoded = lightningPayReq.decode(invoice.payment_request);`](https://github.com/BlueWallet/LndHub/blob/6b67839414f782c32fad07956b108fa6e39a63fe/class/User.js#L242)

But the decoded pay req would have an amount of 0(this is my understanding of tip invoices, the payee adds the amount as 0 then the payer specifies the amount on payment)

Next LndHub would determine that the invoice has been paid internally 
[`invoice.ispaid = _invoice_ispaid_cache[invoice.payment_hash] || !!(await this.getPaymentHashPaid(invoice.payment_hash))`](https://github.com/BlueWallet/LndHub/blob/6b67839414f782c32fad07956b108fa6e39a63fe/class/User.js#L257)

Since the invoice has been paid internally the redis lookup would return `true` and lnd invoice lookup block would be skipped

The returned value of the paid invoice would be set as 

[`invoice.amt = decoded.satoshis;`](https://github.com/BlueWallet/LndHub/blob/6b67839414f782c32fad07956b108fa6e39a63fe/class/User.js#L273)

Where `decoded.satoshis` would be 0 since the original added invoice has a value of 0 sats

This would mean that the internal User A's balance has been credited since they have the true amount paid saved in [`await u.savePaidLndInvoice`](https://github.com/BlueWallet/LndHub/blob/6b67839414f782c32fad07956b108fa6e39a63fe/controllers/api.js#L180) but internal User B does not receive the funds since his amount is debited for the original invoice value, which for tip invoices is 0

Please point out if I am missing something here as I do not see how this would work for tip invoices.

**Comment by Overtorment** [comment]
Easy. Tip invoices are not supported.

**Comment by seanaye** [comment]
@Overtorment 😅that would explain a lot. Thank you. Are there plans to support this in the future?
My current understanding is that paying an external tip invoice is allowed but internal tip invoices of any type are unsupported. Is this correct?

**Comment by Overtorment** [comment]
Correct.
No plans, but that might change in future.
