### ISSUE TITLE
Insecure TLS Configuration

### ISSUE THREAD

**Issue by MG-ng** [BlueWallet/LndHub#542]
Is adding (a tutorial showing how to add) a self signed certificate to the installed certificates maybe a better solution here?

https://github.com/BlueWallet/LndHub/blob/0964ebfca5ba3d0fdec35f110b57054659a1d20b/index.js#L6

**Comment by Overtorment** [comment]
tls termination is out of scope.

what we should add is probably mention of caddy/nginx/letsencrypt/etc
