### ISSUE TITLE
Problems in Lightning import Wallet

### ISSUE THREAD

**Issue by cauangregui04** [BlueWallet/LndHub#549]
When i try import my lightning wallet the error "import error: API failure: Error undefined" is prompt

**Comment by mezagama** [comment]
I have the same problem

**Comment by cauangregui04** [comment]
Hi @mezagama  , i discovered the solution in this link https://bluewallet.io/docs/recover-lndhub/

The service LnDHub is disable.

**Comment by Overtorment** [comment]
@TommyBuho you can email me at i@bluewallet.io with your details, Ill look up your submission
