### ISSUE TITLE
Wallet Export doesn't match wallet details

### ISSUE THREAD

**Issue by HamishMacEwan** [BlueWallet/LndHub#57]
I have a lightning lndhub wallet hosted on my own local lndhub instance (from myNodeBTC.com) and the backup/export has (and should) read:

`lndhub://REDACTED:REDACTED@http://192.168.1.XX:3000/`

However, since importing another wallet (with the same redacted values) at the same node on a different IP address (a public IP), backup/export now reads:

`lndhub://REDACTED:REDACTED@http://203.86.207.XX:3000/`

And so do other wallets at different addresses on the same node with the same redacted values.

How can I get the correct export/backup values to display please?

**Comment by Overtorment** [comment]
I think its a feature, not a bug.
Sometimes you have public IP, so you connect through public IP, and thats exactly what you might need.
If you want to be connected only while being in the same subnet - then you use local area network IPs (like that one with 192.168).
BlueWallet doesnt really manages IPs, just uses IPs that are fed from settings or export.

If you really need to change the IP you can manually edit export string and put the correct IP there.

**Comment by HamishMacEwan** [comment]
I want to be able to access the account both via public IP and private IP without editing the single entry I'm allowed for REDACTED:REDACTED.  

That is to have an account @192.168.x.x, and @203.86.207.xx, so that when I'm at home I can use the private IP version, and when out, the public IP account can be selected.

My description of my problem was poor.  It should have made it clear this feature means BlueWallet will not allow accounts per address but only one account with the latest imported address.

**Comment by Overtorment** [comment]
i didnt get it, so whats the issue?

**Comment by Anatoltol** [comment]
Very good wallet
