### ISSUE TITLE
Balance of connected Bluewallets

### ISSUE THREAD

**Issue by ArbenKarb** [BlueWallet/LndHub#60]
Is there a way to query

a) How many user wallets are connected to the LNDHub
b) What the balance of those "accounts" are?

**Comment by Overtorment** [comment]
a) in redis console `keys user_*`
b) `./node_modules/.bin/babel-node  ./scripts/show_user.js <userid here>`

or reading script `./scripts/show_user.js` can give you ideas on how to navigate database and calculate some stats.
