### ISSUE TITLE
Condition repeated: if (!info.num_satoshis && !info.num_satoshis) 

### ISSUE THREAD

**Issue by educob** [BlueWallet/LndHub#7]
Hi. Thanks for this project.

In https://github.com/BlueWallet/LndHub/blob/master/controllers/api.js line 190:
`if (!info.num_satoshis && !info.num_satoshis) {`

Same condition checked twice so I guess that the intention was to check 2 conditions.

I take the chance to kindly ask if I could talk to you guys to solve some doubts I have. For instance I haven't seen anything about channels and as I understand it one cannot add funds to an open channel so each user should open a channel with his funds. Is that so?

**Comment by Overtorment** [comment]
Hello! Thanks for pointing this bug out. Not critical, but will clean it up anyways.

LndHub is a wrapper around LND, all channels should be managed via `lncli` directly. Obviously, I do that for default LndHub (the one that BlueWallet connects to by default), but you are free to install your own Lnd & LndHub and configure your BlueWallet to work with that. Actually, I would be happy if youd do that so youre not relying on any custodial service. 

PS. https://medium.com/bluewallet/bluewallet-brings-zero-configuration-lightning-payments-to-ios-and-android-30137a69f071
