### ISSUE TITLE
Where can I see wallet that was made on Bluewallet on the server?

### ISSUE THREAD

**Issue by maltokyo** [BlueWallet/LndHub#87]
Sorry maybe a stupid question, and I can't find in the documentation.

1. I setup LND and successfully connected LNDHub and am using it from Bluewallet.

2. I can see in lncli the wallet that was set up when I installed LND.  No issues so far.

3. After this, in Bluewallet I have set up a (separate?) Lightning wallet.  Where can I verify/see this using `lncli` on the server?  Where does it "exist" and how is it backed up?

**Comment by Overtorment** [comment]
easiest way to verify this is open your LN wallet on bluewallet, open 'export' and see that your credentials end with your server's IP.

other way is to create an invoice on BW, and you should see this exact invoice when you run `lncli listinvoices` on server.
or, payee pubkey of this invoice should match pubkey from `lncli getinfo`

physically, LNDHUB accounts are stored in redis database
