### ISSUE TITLE
Invoice payment stuck

### ISSUE THREAD

**Issue by corbelantoine** [BlueWallet/LndHub#9]
Issue raised on Lnd github page and redirected here:
https://github.com/lightningnetwork/lnd/issues/2524

### Background

I have a direct channel opened to BlueWallet's node (03021c5f5f57322740e4ee6936452add19dc7ea7ccf90635f95119ab82a62ae268).
The channel is sufficiently funded and the connexion is not broken:
`lncli connect 03021c5f5f57322740e4ee6936452add19dc7ea7ccf90635f95119ab82a62ae268@207.180.244.165:9735
[lncli] rpc error: code = Unknown desc = already connected to peer: 127.0.0.1:33862`
--> I'm using reverse port forwarding as a proxy

### Your environment

* version of `lnd`
`lnd --version
lnd version 0.5.1-beta commit=v0.5.1-beta-343-g55b580f2b80d2e62af4067d3ddf8688614bf0914`

* which operating system (`uname -a` on *Nix)
Linux HOST_NAME 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

* version of `btcd`, `bitcoind`, or other backend
Bitcoin Core Daemon version v0.17.1

* any other relevant environment details
Tor is setup. There is two ways to connect to me: Tor onion v2 or using an ipv4 public IP on an AWS server that forwards everything on port 9735 to my localhost.

### Steps to reproduce
Create an invoice on bluewallet app:
`lnbc1u1pwyvyhypp5mzretv6qjjg3c2s50sws6nnepua473n4lf6ruqsm0aruh7flspasdq823jhxaqcqzysfsmkfs7qgw3v557fs20h4xrj5kma9wfmd57snx2kxxkutysdx3ws8ez0qjl7crla93vsnr4sgtp9u537cwh3pqtv0t3srm3qcnwzaecpgvenqc`

`lncli payinvoice XXX...`

### Expected behaviour

Payment should be paid instantly.

### Actual behaviour

`lncli payinvoice lnbc1u1pwyvyhypp5mzretv6qjjg3c2s50sws6nnepua473n4lf6ruqsm0aruh7flspasdq823jhxaqcqzysfsmkfs7qgw3v557fs20h4xrj5kma9wfmd57snx2kxxkutysdx3ws8ez0qjl7crla93vsnr4sgtp9u537cwh3pqtv0t3srm3qcnwzaecpgvenqc
Description: Test
Amount (in satoshis): 100
Destination: 03021c5f5f57322740e4ee6936452add19dc7ea7ccf90635f95119ab82a62ae268
Confirm payment (yes/no): yes`

Payment stuck here. No log being displayed (as INFO).
While this is stuck I could send some sats to the app "Wallet of Satoshi" and pay the same invoice from there.
This also happened yesterday, I wanted to wait in case it was a network issue.

State of the channel:
"capacity": "450000",
"local_balance": "45950",
"remote_balance": "403604",
"commit_fee": "446",
"commit_weight": "724",
"fee_per_kw": "616",
"unsettled_balance": "0",
"total_satoshis_sent": "403604",
"total_satoshis_received": "0",
"num_updates": "2",
"pending_htlcs": [
],
"csv_delay": 144,
"private": false

**Comment by Overtorment** [comment]
Hello! I see your channel had at least one successfull update since you posted:

```
            "capacity": "450000",
            "local_balance": "403604",
            "remote_balance": "44643",
            "commit_fee": "1753",
            "commit_weight": "724",
            "fee_per_kw": "2421",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "403604",
            "num_updates": "3",
            "pending_htlcs": [
            ],
            "csv_delay": 144,
            "private": false
        },
```

LND is known to be a bit "frisky", sometimes it stops operating without very noticeable signs, so even payments through direct channel wont go through. Quick fix is to restart the node (I do it regularly for our node). LND is expected to introduce more 'health' metrics in further releases.

Signs of LND needing a restart:
* `time lncli getinfo` takes significant amount of time (more than 1 sec..?)
* payments are not going through

**Comment by Overtorment** [comment]
LMK how it goes

**Comment by corbelantoine** [comment]
I just restarted my node and jumped from 2 to 6 updates.
I think I was stuck at the 3rd payment because you updated and I didn't. For a short moment I could see the pending htlc appear.
Are you also using LND? I'm closing this issue because it is definitely an issue with LND.

**Comment by Overtorment** [comment]
Thanks for the update!
