### ISSUE TITLE
myNodeBTC 0.2.12 Has Issue with LndHub 

### ISSUE THREAD

**Issue by HamishMacEwan** [BlueWallet/LndHub#90]
Hi,

Since the 0.2.12 upgrade of myNodeBTC.com there have been issues with LndHub access. @tehelsper curates the distribution.

I have attached more extensive logs, but the effective error appears in this excerpt:

```
Jul 27 18:16:48 myNode lndhub[5191]: dfff1474-5f6d-405c-8545-444f060ea0b9 ::ffff:192.168.1.153 - - [27/Jul/2020:06:16:48 +0000] "GET /getuserinvoices?limit=200 HTTP/1.1" 200 1851 "-" "okhttp/3.12.1"
Jul 27 18:16:48 myNode lndhub[5191]: 2020-07-27T06:16:48.636Z : info: [] : ["e2c6800e-fb60-4098-9188-11b267b35301","error gettxs:","{\"result\":null,\"error\":{\"code\":-19,\"message\":\"Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path).\"},\"id\":\"528a4f72-9f3a-488c-bd3a-f9fefdea28ab\"}\n","userid:","6794f99768dc8a8de593ee8101d357cce35f2dcb12c07a28"]
Jul 27 18:16:48 myNode lndhub[5191]: e2c6800e-fb60-4098-9188-11b267b35301 ::ffff:192.168.1.153 - - [27/Jul/2020:06:16:48 +0000] "GET /gettxs HTTP/1.1" 200 2 "-" "okhttp/3.12.1"

```  
It has been noted that 

`error\":{\"code\":-19,\"message\":\"Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path)`

suggests `bitcoind` is not happy with some RPC call...

@tehelsper is happy to assist with any questions regarding the myNodeBTC.com setup to manage LndHub's launch and operation.

If there is any additional information you require please just ask.

[2020-07-27T21_35_28_328Z-debug.log](https://github.com/BlueWallet/LndHub/files/4992770/2020-07-27T21_35_28_328Z-debug.log)
[lndhub-july27170610.log](https://github.com/BlueWallet/LndHub/files/4992771/lndhub-july27170610.log)

**Comment by Overtorment** [comment]
Quick googling showed that the issue might be because your bitcoin core has more than 1 wallet and some RPC calls are not prepared for that 
https://github.com/bitcoin/bitcoin/issues/11257

Lndhub uses following RPC calls: `importaddress`, `listtransactions`, `getblockchaininfo`. Looking at logs, its probably failing at listtransactions. Are you able to run the following via bitcoin-cli: `listtransactions * 100500 0 true`  ?

if thats the case, then the fix would be: in config file you would have to add `/wallet/<wallet_name>` to  `config.bitcoind.rpc`





Just for any case: was bitcoin core version upgraded in `0.2.12`? A while ago Lndhub relied on deprecated `accounts` RPC, but I thought we refactored that. So my second bet is that the issue is somewhere here.

**Comment by HamishMacEwan** [comment]
Yes, since the incorporation of Specter into the myNodeBTC.com distribution (v0.2.11) there have been two wallets:

```
>>> listwallets
[
  "wallet.dat",
  "spectercc965c6d9e62fa00/simple_"
]

```
Which caused problems for joinmarket until the wallet was specified in bitcoin.config:

```
# Specter, joinmarket wallet resolution 
# Removed for temporary testing lndhub issues with "wallet selection" but unsuccessfully
main.wallet=wallet.dat
```
Running the command you gave resulted in:
```
>>> listtransactions "*" 100500 0 true
error code: -19
error message:
Wallet file not specified (must request wallet RPC through /wallet/ uri-path).
Try adding "-rpcwallet=" option to bitcoin-cli command line.

>>>
```

So following your suggestion, but unable to find `config.bitcoind.rpc` I've extended the line in `config.js` to read:

`rpc: 'http://mynode:[password]@127.0.0.1:8332/wallet/wallet.dat'`

And SUCCESS!

Thank you @Overtorment.  Buy you a beverage next time we meet online!

**Comment by BitcoinQnA** [comment]
Awesome stuff @HamishMacEwan

**Comment by HamishMacEwan** [comment]
Thank you, though I think @Overtorment deserves most of the credit, particularly for the information (which I had sought, sort of) as to where all the RPC configuration was.

**Comment by Overtorment** [comment]
![it-юмор-geek-3596647](https://user-images.githubusercontent.com/1913337/71772469-2814fd80-2f43-11ea-9cac-6fd80d12dd75.gif)

**Comment by tehelsper** [comment]
Awesome, I can push this update in the next myNode version.
