### ISSUE TITLE
New install - Can't send payment

### ISSUE THREAD

**Issue by liquidso** [BlueWallet/LndHub#98]
Problem description:

- Payment to an invoice fails.

Environment:

- lnd v0.11.0-beta
- lnd v0.10.4-beta
- Lndhub latest

Logs:

LndHub: info: []"error running getCalculatedBalance():","{\"result  :\":null,\"error\":{\"code\":-18,\"message\":\"Requested wallet does not exist or is not loaded\"},\"id\":\...

Bluewallet: API error: your previous payment is in transit, try again in 5 minutes (code 9)

Additional context.

- Tried with both LND version 11 and 10 so it seems to be something within Lndhub. 
- Receiving payment works fine.

**Comment by Overtorment** [comment]
1) you need to explicitly configure your bitcoind to use specific wallet, see example here: https://github.com/BlueWallet/LndHub/blob/988ac805d0a11453edec64af05dbc4c32301035d/config.js#L3

2) most likely fixing #1  will fix everything.  if you really have stuck payments, then simply wait for a timeout (I don't remember the default value, its between 5min-1h), and then run unlocking script   https://github.com/BlueWallet/LndHub/blob/master/run-process-locked.sh

**Comment by liquidso** [comment]
Thanks for the reply. 

There was no wallet name "wallet" in bitcoind data directory so I created a new wallet naming it 'wallet" to make it exactly same as the example and updated the config.js and re-babel on lndhub server.

bitcoin/data/wallet/ls >>
database  db.log  wallet.dat

Updated the config.js as:
rpc: 'http://login:password@1.1.1.1:8332/wallet/wallet.dat', 

babel ./ --out-dir ./build --copy-files --ignore node_modules

Unfortunately I'm still get the same error. 
(node:8046) UnhandledPromiseRejectionWarning: Error: {"result":null,"error":{"code":-18,"message":"Requested wallet does not exist or is not loaded"},"id":"3c9a53b3-e6e0-4105-aa09-a98832d6610a"}

    at IncomingMessage.<anonymous> (/root/LndHub/node_modules/jayson/lib/client/http.js:76:23)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:8046) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8046) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

On the side note, I'm running the latest bitcoind version.

bitcoin-cli -getinfo
{
  "version": 200100,

**Comment by Overtorment** [comment]
can you make `listwallets` rpc call? for example:

```
# ./bitcoin-0.17.0/bin/bitcoin-cli -rpcuser=uuu -rpcpassword=ppp  listwallets
[
  "",
  "wallet.dat"
]
```


also, error message suggests you do `loadwallet` on your cli to make it work

**Comment by Overtorment** [comment]
also, just for any case, try starting lndhub like this: `./node_modules/.bin/babel-node index.js`

**Comment by liquidso** [comment]
It shows the directory of the wallet not the actual wallet with .dat file extension...

# bitcoin-cli -rpcuser=uuu -rpcpassword=ppp -rpcconnect=x.x.x.x listwallets
[
  "",
  "wallet"
]

**Comment by Overtorment** [comment]
so, instead of a `wallet.dat` use just `wallet` in lndhub config

**Comment by liquidso** [comment]
Thanks! that did the trick :+1:
